export const ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  TRAIN_ALREADY_EXISTS: "TRAIN_ALREADY_EXISTS",
  TRAIN_NOT_FOUND: "TRAIN_NOT_FOUND",
  TRAIN_NO_OPERATING_DAYS_CONFIGURED: "TRAIN_NO_OPERATING_DAYS_CONFIGURED",
  TRAIN_NOT_OPERATING_ON_DAY: "TRAIN_NOT_OPERATING_ON_DAY",
  TRAIN_OPERATING_DAYS_REFERENCED: "TRAIN_OPERATING_DAYS_REFERENCED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
