export const ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  // Train Error Codes
  TRAIN_ALREADY_EXISTS: "TRAIN_ALREADY_EXISTS",
  TRAIN_NOT_FOUND: "TRAIN_NOT_FOUND",
  TRAIN_NO_OPERATING_DAYS_CONFIGURED: "TRAIN_NO_OPERATING_DAYS_CONFIGURED",
  TRAIN_NOT_OPERATING_ON_DAY: "TRAIN_NOT_OPERATING_ON_DAY",
  TRAIN_OPERATING_DAYS_REFERENCED: "TRAIN_OPERATING_DAYS_REFERENCED",

  // Coach Error Codes
  COACH_ALREADY_EXISTS: "COACH_ALREADY_EXISTS",
  COACH_NOT_FOUND: "COACH_NOT_FOUND",
  SEATS_ALREADY_GENERATED: "SEATS_ALREADY_GENERATED",

  // seat Error Codes
  SEAT_NOT_FOUND: "SEAT_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
