export const ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  // Train Error Codes
  TRAIN_ALREADY_EXISTS: "TRAIN_ALREADY_EXISTS",
  TRAIN_NOT_FOUND: "TRAIN_NOT_FOUND",
  TRAIN_NO_OPERATING_DAYS_CONFIGURED: "TRAIN_NO_OPERATING_DAYS_CONFIGURED",
  TRAIN_NOT_OPERATING_ON_DAY: "TRAIN_NOT_OPERATING_ON_DAY",
  TRAIN_OPERATING_DAYS_REFERENCED: "TRAIN_OPERATING_DAYS_REFERENCED",

  // Coach Error Codes
  COACH_ALREADY_EXISTS: "COACH_ALREADY_EXISTS",
  COACH_NOT_FOUND: "COACH_NOT_FOUND",
  SEATS_ALREADY_GENERATED: "SEATS_ALREADY_GENERATED",

  // seat Error Codes
  SEAT_NOT_FOUND: "SEAT_NOT_FOUND",

  // statio Error Codes
  STATION_ALREADY_EXISTS: "STATION_ALREADY_EXISTS",
  STATION_NOT_FOUND: "STATION_NOT_FOUND",
  STATION_DEACTIVATED: "STATION_DEACTIVATED",

  // Route Error Codes
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  ROUTE_ALREADY_EXISTS: "ROUTE_ALREADY_EXISTS",
  ROUTE_REFERENCED_BY_SCHEDULES: "ROUTE_REFERENCED_BY_SCHEDULES",
  ROUTE_MIN_STATIONS_REQUIRED: "ROUTE_MIN_STATIONS_REQUIRED",
  ROUTE_STATION_NOT_FOUND: "ROUTE_STATION_NOT_FOUND",
  STATION_ALREADY_ON_ROUTE: "STATION_ALREADY_ON_ROUTE",
  STOP_NUMBER_CONFLICT: "STOP_NUMBER_CONFLICT",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
