import "@irctc/openapi";
import { z } from "zod";

/**
 * Zod validation schema for POST /api/v1/payments/verify request body.
 */
export const verifyPaymentSchema = z
  .object({
    paymentOrderId: z.uuid().optional().openapi({
      example: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
      description: "Internal payment order UUID",
    }),
    razorpayOrderId: z.string().min(1, "razorpayOrderId is required").openapi({
      example: "order_9A33XWKAAKKA89",
      description: "Razorpay order ID",
    }),
    razorpayPaymentId: z
      .string()
      .min(1, "razorpayPaymentId is required")
      .openapi({
        example: "pay_2938491823912",
        description: "Razorpay payment transaction ID",
      }),
    razorpaySignature: z
      .string()
      .min(1, "razorpaySignature is required")
      .openapi({
        example: "a3f5e71...",
        description: "HMAC hex signature generated by Razorpay",
      }),
  })
  .openapi("VerifyPaymentRequest");

export type VerifyPaymentDto = z.infer<typeof verifyPaymentSchema>;

/**
 * Zod validation schema for payment verification response.
 */
export const verifyPaymentResponseSchema = z
  .object({
    paymentOrderId: z.uuid().openapi({
      example: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
    }),
    razorpayOrderId: z.string().openapi({
      example: "order_9A33XWKAAKKA89",
    }),
    razorpayPaymentId: z.string().openapi({
      example: "pay_2938491823912",
    }),
    status: z.string().openapi({
      example: "CAPTURED",
    }),
  })
  .openapi("VerifyPaymentResponse");

export type VerifyPaymentResponseDto = z.infer<
  typeof verifyPaymentResponseSchema
>;

/**
 * Zod validation schema for payment order ID URL parameters.
 */
export const paymentOrderIdParamSchema = z
  .object({
    paymentOrderId: z.uuid("Invalid paymentOrderId format").openapi({
      example: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
    }),
  })
  .openapi("PaymentOrderIdParam");

export type PaymentOrderIdParamDto = z.infer<typeof paymentOrderIdParamSchema>;

/**
 * Zod schema for webhook response.
 */
export const webhookResponseSchema = z
  .object({
    received: z.boolean().openapi({ example: true }),
    event: z.string().optional().openapi({ example: "payment.captured" }),
  })
  .openapi("WebhookResponse");

export type WebhookResponseDto = z.infer<typeof webhookResponseSchema>;

/**
 * Zod validation schema for POST /api/v1/payments/:paymentOrderId/refund request body.
 */
export const refundPaymentRequestSchema = z
  .object({
    amount: z.string().optional().openapi({
      example: "2450.00",
      description: "Amount to refund (defaults to full captured amount)",
    }),
    reason: z.string().optional().openapi({
      example: "User requested refund",
      description: "Reason for refund",
    }),
  })
  .openapi("RefundPaymentRequest");

export type RefundPaymentRequestDto = z.infer<
  typeof refundPaymentRequestSchema
>;

/**
 * Zod validation schema for POST /api/v1/payments/:paymentOrderId/refund response.
 */
export const refundPaymentResponseSchema = z
  .object({
    paymentId: z.string().openapi({
      example: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
      description: "Internal payment ID or order ID",
    }),
    refund: z.object({
      id: z.string().nullable().openapi({
        example: "rfnd_mock_12345",
      }),
      status: z.enum(["PENDING", "PROCESSED", "FAILED"]).openapi({
        example: "PENDING",
      }),
      amount: z.string().openapi({
        example: "2450.00",
      }),
      currency: z.string().default("INR").openapi({
        example: "INR",
      }),
    }),
  })
  .openapi("RefundPaymentResponse");

export type RefundPaymentResponseDto = z.infer<
  typeof refundPaymentResponseSchema
>;
