/**
 * Orval Input Transformer — Error Component Deduplication
 *
 * Collapses every error response in the OpenAPI spec into a single shared
 * `ErrorResponse` reference so that the React Query client generated by orval
 * produces one `ErrorResponse` TypeScript type rather than one duplicate file
 * per endpoint and per status code (`login401.ts`, `sendOtp409Error.ts`, etc.).
 *
 * Detection has two paths:
 *
 *   1. Named components (`BadRequestErrorResponse`, `RateLimitErrorResponse`, …)
 *      registered as `x-sdk-ref: "ErrorResponse"` in `components.schemas`. The
 *      transformer's `processResponseMediaType` matches these by `$ref` and
 *      rewrites them to `ErrorResponse`. After rewriting, the named components
 *      are removed from `components.schemas` so orval does not emit a
 *      TypeScript file per variant.
 *
 *   2. Inline error envelopes (anonymous schemas with `properties.success (false)
 *      + properties.error + properties.meta`). These occur in `registry.ts`
 *      where `createErrorResponseSchema(...)` is called without a `schemaName`
 *      argument. The transformer's `processResponseMediaType` matches these
 *      structurally and rewrites them to `ErrorResponse` as well.
 *
 * Per-endpoint examples are extracted from both paths and attached to the
 * media type so the generated SDK and the rendered spec still surface them.
 */

type HttpMethod =
  "get" | "post" | "put" | "patch" | "delete" | "options" | "head"

type OpenApiSchema = {
  properties?: Record<string, OpenApiSchema>
  example?: unknown
  enum?: readonly unknown[]
  $ref?: string
  type?: string
  [key: string]: unknown
}

type MediaTypeObject = {
  schema?: OpenApiSchema
  example?: unknown
  [key: string]: unknown
}

type ResponseObject = {
  content?: {
    "application/json"?: MediaTypeObject
    [key: string]: MediaTypeObject | undefined
  }
  [key: string]: unknown
}

type OperationObject = {
  responses?: Record<string, ResponseObject>
  [key: string]: unknown
}

type PathItemObject = Partial<Record<HttpMethod, OperationObject>> &
  Record<string, unknown>

type OpenAPIObject = {
  components?: {
    schemas?: Record<string, OpenApiSchema>
  }
  paths?: Record<string, PathItemObject>
}

const ERROR_RESPONSE_REF = "#/components/schemas/ErrorResponse"
const SCHEMAS_PATH_PREFIX = "#/components/schemas/"
const HTTP_METHODS: readonly HttpMethod[] = [
  "get",
  "post",
  "put",
  "patch",
  "delete",
  "options",
  "head",
] as const

/**
 * Names of components that should be preserved in `components.schemas` even
 * after deduplication. `ErrorResponse` is the target that the rewrite points
 * at; `ErrorDetail` is the nested type carried by every error envelope.
 */
const PRESERVED_COMPONENT_NAMES = new Set(["ErrorResponse", "ErrorDetail"])

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Build an example object from a schema's inline property examples.
 * Walks `properties` and collects each field's `example` value.
 */
function extractExampleFromSchema(
  schema: OpenApiSchema
): Record<string, unknown> | undefined {
  const properties = schema.properties
  if (!properties) return undefined

  const example: Record<string, unknown> = {}
  let hasAny = false

  for (const [key, prop] of Object.entries(properties)) {
    if (prop.example !== undefined) {
      example[key] = prop.example
      hasAny = true
    } else if (prop.properties) {
      const nested = extractExampleFromSchema(prop)
      if (nested) {
        example[key] = nested
        hasAny = true
      }
    }
  }

  return hasAny ? example : undefined
}

/**
 * Check whether an inline schema matches the error envelope shape:
 * `{ properties: { success (false), error, meta } }`. The `x-sdk-ref` shortcut
 * is not used here because inline envelopes don't carry it.
 */
function isInlineErrorEnvelope(schema: OpenApiSchema): boolean {
  const properties = schema.properties
  if (!properties) return false

  const successProp = properties.success
  const isSuccessFalse =
    successProp?.enum?.includes(false) || successProp?.example === false

  return Boolean(isSuccessFalse && properties.error && properties.meta)
}

/**
 * Rewrite a single response media type to point at `ErrorResponse`. Returns
 * `true` if the rewrite happened so the caller can short-circuit.
 */
function processResponseMediaType(
  mediaType: MediaTypeObject,
  componentExamples: Map<string, Record<string, unknown>>
): boolean {
  const schema = mediaType?.schema
  if (!schema) return false

  // Case A: $ref to a named error component.
  if (schema.$ref) {
    const refName = schema.$ref.replace(SCHEMAS_PATH_PREFIX, "")
    if (PRESERVED_COMPONENT_NAMES.has(refName)) return false
    if (!componentExamples.has(refName)) return false

    const example = componentExamples.get(refName)
    if (example && !mediaType.example) {
      mediaType.example = example
    }
    mediaType.schema = { $ref: ERROR_RESPONSE_REF }
    return true
  }

  // Case B: inline error envelope.
  if (isInlineErrorEnvelope(schema)) {
    const example = extractExampleFromSchema(schema)
    if (example && !mediaType.example) {
      mediaType.example = example
    }
    mediaType.schema = { $ref: ERROR_RESPONSE_REF }
    return true
  }

  return false
}

/**
 * Walk every path response and rewrite error schemas to `ErrorResponse`.
 */
function rewriteErrorResponses(
  paths: Record<string, PathItemObject>,
  componentExamples: Map<string, Record<string, unknown>>
): void {
  for (const pathItem of Object.values(paths)) {
    for (const method of HTTP_METHODS) {
      const operation = pathItem[method]
      if (!operation?.responses) continue

      for (const response of Object.values(operation.responses)) {
        const mediaType = response?.content?.["application/json"]
        if (mediaType) {
          processResponseMediaType(mediaType, componentExamples)
        }
      }
    }
  }
}

// ─── Core Transformer ─────────────────────────────────────────────────────────

/**
 * Orval Input Transformer entry point.
 */
export default function transformOpenApiSpec(
  inputSpec: OpenAPIObject
): OpenAPIObject {
  const spec = structuredClone(inputSpec)
  const schemas = spec.components?.schemas

  if (schemas) {
    const componentExamples = new Map<string, Record<string, unknown>>()
    const deduplicatedNames: string[] = []

    for (const [name, schema] of Object.entries(schemas)) {
      if (PRESERVED_COMPONENT_NAMES.has(name)) continue

      // Authoritative marker: error variants are tagged with
      // `x-sdk-ref: "ErrorResponse"` by `createErrorResponseSchema`.
      if (schema["x-sdk-ref"] !== "ErrorResponse") continue

      const example = extractExampleFromSchema(schema)
      if (example) {
        componentExamples.set(name, example)
      }
      deduplicatedNames.push(name)
    }

    if (spec.paths) {
      rewriteErrorResponses(spec.paths, componentExamples)
    }

    // Remove the deduplicated variants from `components.schemas` so that
    // orval does not emit a TypeScript file per error variant.
    for (const name of deduplicatedNames) {
      delete schemas[name]
    }
  }

  return spec
}
