export const ERROR_CODES = {
  SCHEDULE_INVENTORY_NOT_FOUND: "SCHEDULE_INVENTORY_NOT_FOUND",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_FORBIDDEN: "BOOKING_FORBIDDEN",
  BOOKING_INVALID_TRANSITION: "BOOKING_INVALID_TRANSITION",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
