export const ERROR_CODES = {
  SCHEDULE_INVENTORY_NOT_FOUND: "SCHEDULE_INVENTORY_NOT_FOUND",
  SCHEDULE_NOT_FOUND: "SCHEDULE_NOT_FOUND",
  SCHEDULE_INACTIVE: "SCHEDULE_INACTIVE",
  TRAIN_ALREADY_DEPARTED: "TRAIN_ALREADY_DEPARTED",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_FORBIDDEN: "BOOKING_FORBIDDEN",
  BOOKING_INVALID_TRANSITION: "BOOKING_INVALID_TRANSITION",
  SEAT_HOLD_FAILED: "SEAT_HOLD_FAILED",
  SEAT_HOLD_EXPIRED: "SEAT_HOLD_EXPIRED",
  SEAT_UNAVAILABLE: "SEAT_UNAVAILABLE",
  INVALID_SEAT_IDS: "INVALID_SEAT_IDS",
  INVALID_ROUTE: "INVALID_ROUTE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
