export const ERROR_CODES = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_LOCKED: "OTP_LOCKED",
  OTP_SESSION_NOT_FOUND: "OTP_SESSION_NOT_FOUND",

  REGISTRATION_SESSION_EXPIRED: "REGISTRATION_SESSION_EXPIRED",
  SESSION_CONTEXT_MISSING: "SESSION_CONTEXT_MISSING",
  SESSION_EXPIRED_OR_REVOKED: "SESSION_EXPIRED_OR_REVOKED",
  SESSION_OWNERSHIP_INVALID: "SESSION_OWNERSHIP_INVALID",

  REFRESH_TOKEN_MISSING: "REFRESH_TOKEN_MISSING",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",

  DEVICE_FINGERPRINT_MISMATCH: "DEVICE_FINGERPRINT_MISMATCH",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
